### ISSUE TITLE
Bug #1

### ISSUE THREAD

**Issue by Aritooo** [Mujaca/Masslinker-Releases#1]
![image](https://user-images.githubusercontent.com/67191675/85201097-faf3b600-b2fc-11ea-9f11-e7fd1dca1fad.png)

Wenn man das Fenster minimiert hat dann ist unter dem Tap "Serienliste" die Suchleiste über denn Anime Reitern geschoben.

**Comment by ScarVite** [comment]
should be fixed ~v.7.0.2
