### ISSUE TITLE
Bug #2 Design Bug

### ISSUE THREAD

**Issue by Aritooo** [Mujaca/Masslinker-Releases#2]
![image](https://user-images.githubusercontent.com/67191675/85201185-9b49da80-b2fd-11ea-9e51-a8554b0c6f57.png)

Es ist nicht Exakt in der Mitte. Es ist egal, ob die Anwendung maximiert ist oder minimiert.^^

**Comment by ScarVite** [comment]
fixed ~v-0.7.2
