### ISSUE TITLE
GDrive Upload  

### ISSUE THREAD

**Issue by Aritooo** [Mujaca/Masslinker-Releases#22]
![image](https://user-images.githubusercontent.com/67191675/85630428-e5bbb600-b673-11ea-813d-ab335363dc6f.png)
Es kommt immer Ein Error

**Comment by ScarVite** [comment]
@Aritooo welche Masslinker Version benutzt du?

**Comment by Mujaca** [comment]
das ist die neuste
erkennbar an der "Lang" Auswahl

**Comment by Mujaca** [comment]
Per DC geklärt
