### ISSUE TITLE
API Keys Werden nicht Richtig gespeichert/gelöscht 

### ISSUE THREAD

**Issue by Aritooo** [Mujaca/Masslinker-Releases#24]
Alles Unter den Überschriften Ersetzen/Löschen. **Die Überschriften Bitte stehen Lassen**
**Beschreibe den bug**
Es Kommt Bei der GDrive immer zu einem Error wenn ich was hochladen will.

**Schritte zum Reproduzeieren**
Schritte zum Reproduzieren des bugs:
Einfach wenn man die Folge Hochladen will 

**Erwartetes Verhalten**
Das es Funktioniert so wie vorgesehen 

**Screenshots**
![image](https://user-images.githubusercontent.com/67191675/85842009-3c71de80-b79f-11ea-985a-39e649d004a5.png)

**Zusätzliche Infos**
Müssen wir Noch irgendwas Wissen

**Comment by ScarVite** [comment]
bei mir gehts. kläre das mit ihm privat.
