### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Aritooo** [Mujaca/Masslinker-Releases#35]
Also Der Bug ist mal wieder ein Error 500
Er dritt auf wenn man anscheinend ein zu großes Bild  einsetzt

Schritte zum Reproduzieren des bugs:
1. Erstelle eine neue Show
2. Fülle alles aus und lade ein 2mb großes bild hoch
3. und es kommt ein Error 500

Was Sollte Passieren?
Es sollte die Show abschicken oder eine Fehler Meldung kommen das die Datei zu groß ist

**Comment by ScarVite** [comment]
fixed ~v.0.7.7
