### ISSUE TITLE
Serienliste - Suche

### ISSUE THREAD

**Issue by Aritooo** [Mujaca/Masslinker-Releases#41]
Bitte Beschreibe Klar, was der Bug tut
Ich kann die suche in der Serienliste nicht benutzen. Ich gebe was ein und es passiert nichts.

Schritte zum Reproduzieren des bugs:
1. Gehe auf Serienliste.
2. Dann auf die suche und versuche ein Anime zu finden.

Was Sollte Passieren?
Der Anime den ich eingegeben habe, sollte angezeigt werden.

Bitte Falls möglich Screenshots/Videos hinzufügen

Müssen wir Noch irgendwas Wissen
Suzune hatte das in der letzeren Version, also v0.7.7 auch schon ka wie es jetzt ist. Ich hatte es zu dem zeit punkt noch nicht, kam erst mit diesem Update bei mir der Bug.

**Comment by Aritooo** [comment]
@ScarVite hier ist die issue ka wie ich dich genau vorschlagen sollte ich glaube so geht es auch xD

**Comment by ScarVite** [comment]
Weis glaub genau woran dad liegt

**Comment by ScarVite** [comment]
fixed ~v.0.8.9
