### ISSUE TITLE
Wünsche werden nicht neu gefetched

### ISSUE THREAD

**Issue by Mujaca** [Mujaca/Masslinker-Releases#44]
**Beschreibe den bug**
Die Wünsche werden nicht, beim drücken auf den refetch button neu gefetched.

**Schritte zum Reproduzieren**
Schritte zum Reproduzieren des bugs:
1. Gehe zu den Wünschen
2. Drücke auf den aktuallisieren Button
3. Warte auf den Networkerror

**Erwartetes Verhalten**
Er **sollte** die Wünsche neu fetchen

**Screenshots**
http://totally-not.a-sketchy.site/4VDeBGt.png

**Zusätzliche Infos**
Scar ist ein Kek

**Comment by ScarVite** [comment]
duplicate #42 
ich bin aber auch mit daran schuld
