### ISSUE TITLE
Episoden werden nicht gespeichert

### ISSUE THREAD

**Issue by Aritooo** [Mujaca/Masslinker-Releases#47]
Bitte Beschreibe Klar, was der Bug tut

Schritte zum Reproduzieren des bugs:
1. Episode abschicken
2.  kein Error 
3. Episode wird ausgelassen 

Was Sollte Passieren?die Episode sollte erstellt werden 
Episode sollte erstellt werden

**Comment by ScarVite** [comment]
war etwas komplexer, is aber gefixt @8.0.1
