### ISSUE TITLE
Hoster linke Erkennung 

### ISSUE THREAD

**Issue by Aritooo** [Mujaca/Masslinker-Releases#48]
Eine detaillierte Beschreibung, was dein Problem ist.
ihr müsst was machen

Eine klare Beschreibung, was die neue Funktion können soll. Gerne eine Schritt für Schritt anleitung.
Playtube linke Erkennung im Masslinker 
da er ja demnächst hinzugefügt wird

**Comment by ScarVite** [comment]
hoster werden automatisch erkannt :kek:
Closed
