### ISSUE TITLE
Webp Bilder Support hinzufügen

### ISSUE THREAD

**Issue by xILikepuddingx** [Mujaca/Masslinker-Releases#56]
**Ist dein Vorschlag mit irgendeinem Problem verbunden? Wenn ja beschreibe welches**
Eine detaillierte Beschreibung, was dein Problem ist.
Siehe unten

**Beschreibe wie du es gerne hättest**
Eine klare Beschreibung, was die neue Funktion können soll. Gerne eine Schritt für Schritt anleitung.
Zurzeit kann man ja glaube ich nur PNG und JPG Bilder hinzufügen. Die Anbieter jedoch stellen alle auf Webp um und wir dementsprechend fast nur noch webp Bilder bekommen. Diese müssen wir umwandeln damit diese vom Linker (Seite vermutlich auch) angemommen wird.

Deswegen bitte ich hier um Unterstützung des webp Formats

**Weitere Sachen**
Noch weitere Anmerkungen, wie zB Screenshots, die uns beim Entwickeln, des Features helfen
siehe oben

**Comment by ScarVite** [comment]
funktuniert.
