### ISSUE TITLE
API Key von Doodstream und GoUnlimited ist verbuggt

### ISSUE THREAD

**Issue by Lequiit** [Mujaca/Masslinker-Releases#6]
Wenn ich API Key beim ersten mal eingebe wird der Key von Go auch bei Dood benutzt.
Ändern geht auch nicht

Links:

https://vivo.sx/8ddd113637
https://vivo.sx/5472675c39
Sorry Links gingen nicht anders.

**Comment by Lequiit** [comment]
Edit: Es läd richtig hoch, wird aber nur falsch unter den settings angezeigt.

**Comment by ScarVite** [comment]
fixed ~v.0.7.2 (Muja ist dumm)
![Code_qvRsHKn3rr](https://user-images.githubusercontent.com/43887376/85208520-80915900-b331-11ea-9118-93e365c699d9.png)
