### ISSUE TITLE
Bei mehreren Folgen hört es einfach auf zu Uploaden

### ISSUE THREAD

**Issue by Lequiit** [Mujaca/Masslinker-Releases#7]
Ich habe Railgun, Staffel 2, 24 Folgen, versucht hochzuladen über die API. 
Dort wurden alle Jetload Links hochgeladen aber nach der Mitte bei den VIVO Links hat es einfach aufgehört zu Uploaden. Ich habe das über die Nacht laufen lassen aber es ist am Morgen auch nichts passiert. 
Am besten muss ich das über Bildschirmübertragung zeigen.

**Comment by ScarVite** [comment]
1. kann es bestätigen durch consolen outputs & Discord Screen Share
2. könnte daran liegen, dass er den upload gespammt hat

**Comment by Lequiit** [comment]
Edit: Wenn ich mehrere Folgen runter/hochlade dann crasht die API.
